# Generated by Django 3.1.7 on 2021-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210315_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='tracker.Type', verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
