# Generated by Django 3.1.7 on 2021-03-18 12:29

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210315_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, validators=[tracker.validators.validate_words_count, tracker.validators.validate_words], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=120, validators=[tracker.validators.validate_string, tracker.validators.validate_words, tracker.validators.MinLengthValidator(3)], verbose_name='Краткое описание'),
        ),
    ]
