# Generated by Django 3.1.7 on 2021-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_profiles', 'Can view profiles')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='githubLink',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Ссылка на гитхаб'),
        ),
    ]
