# Generated by Django 3.1.7 on 2021-04-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20210419_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_members', 'Can update members')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
