# Generated by Django 3.1.7 on 2021-04-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20210419_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
